#
# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

tracing:
  service: jdbc-db

db:
  source: jdbc
  connection:
    url: jdbc:postgresql://127.0.0.1:5432/distribuida
    username: postgres
    password: Cromina1000
    poolName: postgresqlPool
    
    
    
  statements:
    # required ping statement
    ping: "DO 0"
    # SQL to persona
    select-persona : "select * from persona;"
    select-id : "select * from persona where id= ?;"
    delete-persona : "delete from Persona where id = ?;"
    update-persona : "update Persona set nombre = ?,direccion = ?, correo =? where id = ?;"
    insert-persona : "INSERT INTO Persona (id,nombre,direccion,correo) VALUES(?, ?, ?, ?);"
    