server:
    port: 8081
javax:
    sql:
        DataSource:
            personaDataSource:
                dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
                dataSource:
                    url: jdbc:postgresql://127.0.0.1:5432/HelidonDB
                    user: postgres
                    password: Cromina1000
    